# Generated by Django 4.1.1 on 2022-09-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postagem',
            old_name='data_publicação',
            new_name='data_publicacao',
        ),
    ]
