# Generated by Django 4.1.1 on 2022-09-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_data_publicação_postagem_data_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='postagem_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
