# Generated by Django 4.1.1 on 2022-09-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postagem_postagem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='postagem_image',
        ),
    ]
